### PR TITLE
feat: add icons

### PR DESCRIPTION
**Pull request by denistakeda**
This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/react-native-scrollable-tab-view/1)

### CODE REVIEW

**Comment by kennethlynne** [comment]
Reviewed 4 of 9 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 34 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1#-KZLIyU9hpvItmpXYuLH:-KZLIyUAwsbkMI4p8brQ:b28jy8b) ([raw file](https://github.com/edtechfoundry/react-native-scrollable-tab-view/blob/6a377dfbef0236308a97e38ed56798d505d88d9b/README.md#L34)):*
> ```Markdown
>       <ScrollableTabView>
>         <Tab tabLabel="React" icon={<Icon name="react-icon"/>}>
>             <ReactPage tabLabel="React" />
> ```

remove tablabel from children

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1)*

**Comment by kennethlynne** [comment]
Reviewed 5 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1#-:-KZLJI7jPQHUYANYXglG:bnfp4nl)*

**Comment by kennethlynne** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1#-:-KZLL7P1BBl8_v_GcZgn:bnfp4nl)*

**Comment by arealmaas** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-scrollable-tab-view/1#-:-KZLMHb4-HWE0t9RuMyp:bnfp4nl)*

**Pull request merged**
